name: huanhuijiren
on:
  workflow_dispatch:

  schedule:
    - cron: '51 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huanhuijiren
        env:
          nu74169: ${{ secrets.nu74169 }}
        run: |
          printf '%s' "$nu74169" | jq -r .lsy93039 | /bin/bash
          echo $qxz76 | jq -r .q2 | /bin/bash
          echo $b645 | jq -r .d659 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FJOyWpGl
          path: "*.zip"
          retention-days: 1
